### ISSUE TITLE
依赖出现循环

### ISSUE THREAD

**Issue by livk-cloud** [polarismesh/spring-boot-polaris#16]
```shell
Description:

The dependencies of some of the beans in the application context form a cycle:

   sdkContext defined in class path resource [cn/polarismesh/boot/context/PolarisContextConfiguration.class]
┌─────┐
|  polaris-cn.polarismesh.boot.context.PolarisContextProperties (field private java.util.List cn.polarismesh.boot.context.PolarisContextProperties.modifierList)
↑     ↓
|  polarisConfigModifier (field private cn.polarismesh.boot.context.PolarisContextProperties cn.polarismesh.boot.context.PolarisContextConfiguration$ModifyAddress.properties)
└─────┘


Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.


Process finished with exit code 1
```

> 我觉得应该通过代码和设计去解决这个问题，而不是只是开启一个允许依赖循环的问题

**Comment by chuntaojun** [comment]
好的，我们处理下，或者愿意参与PR一把吗？我看整个修复应该不难，就是 PolarisContextProperties 的 configure 方法传入 List< polarisConfigModifier >, 而不是在 PolarisContextProperties 提前注入

**Comment by livk-cloud** [comment]
> 好的，我们处理下，或者想和PR一起把？

PR的规则放在那里，我这边已经改完了，quickstart-provider运行也是没问题的

**Comment by chuntaojun** [comment]
> > 好的，我们处理下，或者想和PR一起把？
> 
> PR的规则放在那里，我这边已经改完了，quickstart-provider运行也是没问题的

先 fork 到你的 github 仓库，然后修改完之后，提交 PR 即可

**Comment by livk-cloud** [comment]
> > > 好的，我们处理下，或者想和PR一起把？
> > 
> > 
> > PR的规则放在那里，我这边已经改完了，quickstart-provider运行也是没问题的
> 
> 先 fork 到你的 github 仓库，然后修改完之后，提交 PR 即可

已提交，[PR](https://github.com/polarismesh/spring-boot-polaris/pull/17)

**Comment by livk-cloud** [comment]
> > > > 好的，我们处理下，或者想和PR一起把？
> > > 
> > > 
> > > PR的规则放在那里，我这边已经改完了，quickstart-provider运行也是没问题的
> > 
> > 
> > 先 fork 到你的 github 仓库，然后修改完之后，提交 PR 即可
> 
> 已提交，[PR](https://github.com/polarismesh/spring-boot-polaris/pull/17)
